name: concrete-damage-detection
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchvision=0.15.2
  - cudatoolkit=11.8
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - opencv=4.8.1
  - pillow=10.0.0
  - tqdm=4.65.0
  - jupyter=1.0.0
  - notebook=7.0.2
  - ipykernel=6.25.0
  - pip=23.2.1

  # Pip-only dependencies
  - pip:
    - ultralytics==8.0.196
    - albumentations==1.3.1
    - pathlib2==2.3.7.post1
    - typing-extensions==4.7.1
    - imageio==2.31.1
    - numba==0.57.1